import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import { AuthProvider } from "@/providers";
import "react-quill/dist/quill.snow.css";
import "react-quill/dist/quill.bubble.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
// import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ToastContainer />

          <div className="dark:bg-slate-800 dark:text-slate-200 min-h-screen flex flex-col">
            <div className="px-4 container mx-auto">
              <Header />

              <div className="min-h-20 py-10">{children}</div>
            </div>
            <div className="mt-auto">
              <Footer />
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
